name: python CI with flask

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      
    - name: setup python env
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - name: Intsall depens
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Tests
      run: pytest

    - name: docker building and pushing
      uses: mr-smithers-excellent/docker-build-push@v7
      with:
        image: kanna1718/python-flask-app
        tags: v1
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
